name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:  # id of input
    description: 'Who to greet'
    required: true
    default: '.'
outputs:
  time: # id of output
    version: 'The version'
runs:
  using: 'node12'
  main: 'index.js'
