name: Test Workflow Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Node Version
      uses: ./.github/actions/ui-version
      id: ui
      with:
        path: "./ui"

    - name: Python Version
      uses: ./.github/actions/api-version
      id: api 
      with:
        path: "./api"

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ca-central-1

    - name: Python AMI
      uses: ./.github/actions/docker-action
      id: python-ami
      with:
        name: "iai-api"
        version: "${{ steps.api.outputs.version }}"
